#conda env create -f environment.yml

name: music-network-env

channels:
 - default
 - conda-forge
 - anaconda
 - bioconda
 - iainsgillis
dependencies:
 - python=3.7 
 - jupyterlab 
 - snakemake
 - numpy 
 - matplotlib
 - pip
 - music21
 - networkx
 - spyder
 - python-igraph
 - scipy
 - pandas
