name: musicnetwork-env

channels:
 - default
 - conda-forge
 - anaconda
 - bioconda
 - iainsgillis
dependencies:
 - python=3.7 
 - ipykernel 
 - snakemake
 - numpy 
 - matplotlib
 - pip
 - music21
 - networkx
